version: "3.9"

services:
  web:
    image: ilulale:expensetracker
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "80:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
